# Generated by Django 6.0 on 2026-01-11 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='Источник')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID вакансии в источнике')),
                ('source_url', models.URLField(verbose_name='URL вакансии')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, verbose_name='Навыки')),
                ('experience_min', models.PositiveIntegerField(default=0, verbose_name='Опыт от')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, verbose_name='Тип занятости')),
                ('remote', models.BooleanField(default=False, verbose_name='Удаленно')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'indexes': [models.Index(fields=['title'], name='vacancies_v_title_f8aa81_idx'), models.Index(fields=['experience_min'], name='vacancies_v_experie_d25d41_idx'), models.Index(fields=['source'], name='vacancies_v_source_d8e818_idx'), models.Index(fields=['is_active'], name='vacancies_v_is_acti_e300ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_vacancy_per_source')],
            },
        ),
    ]
